-- Add new columns to positions table
ALTER TABLE public.positions 
ADD COLUMN IF NOT EXISTS lease_value_km DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS position_label TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS position_type TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS item_name TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS width DOUBLE PRECISION DEFAULT 60,
ADD COLUMN IF NOT EXISTS height DOUBLE PRECISION DEFAULT 60;